package token

import (
	"crypto/rand"
	"fmt"
	"strings"
)

// Codes are the other half of the token package: where a session token is
// generated by a browser's storage and never read by anyone, a code is read off
// a printed sheet, typed with a thumb, or dictated across a counter. So it uses
// Crockford's base32 alphabet — no I, L, O or U, which removes both the 1/I/l
// and 0/O confusions and the one four-letter word the alphabet can spell.
const codeAlphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

// Sixteen characters of a 32-symbol alphabet is 80 bits. Well beyond guessing,
// and still four short groups on screen.
const (
	codeLength    = 16
	codeGroupSize = 4
)

// NewCode returns a code in its display form, grouped for reading aloud:
// XXXX-XXXX-XXXX-XXXX.
func NewCode() (string, error) {
	buf := make([]byte, codeLength)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate code: %w", err)
	}

	var out strings.Builder
	for i, b := range buf {
		if i > 0 && i%codeGroupSize == 0 {
			out.WriteByte('-')
		}
		// 32 divides 256, so the modulo is unbiased.
		out.WriteByte(codeAlphabet[int(b)%len(codeAlphabet)])
	}
	return out.String(), nil
}

// NormalizeCode reduces whatever was typed to the form the hash was taken of.
// Spaces, dashes and case are noise, and Crockford's substitutions mean a
// mistyped O or l is corrected rather than rejected — the person is copying a
// code, not choosing a password, so a typo they cannot see is our problem.
func NormalizeCode(raw string) string {
	var out strings.Builder
	out.Grow(len(raw))

	for _, r := range strings.ToUpper(raw) {
		switch r {
		case 'O':
			out.WriteByte('0')
		case 'I', 'L':
			out.WriteByte('1')
		default:
			if strings.ContainsRune(codeAlphabet, r) {
				out.WriteRune(r)
			}
		}
	}
	return out.String()
}

// HashCode stores and compares a code by its normalized form, so the same code
// typed with different spacing still matches.
func HashCode(raw string) string {
	return Hash(NormalizeCode(raw))
}

// CodePrefix is the rate limiter's second key. Limiting by IP alone lets a
// botnet spread guesses across addresses; limiting by the first group as well
// caps how fast anyone can work through the codes that start the same way,
// whatever address they come from.
func CodePrefix(raw string) string {
	normalized := NormalizeCode(raw)
	if len(normalized) < codeGroupSize {
		return normalized
	}
	return normalized[:codeGroupSize]
}
